[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.11.1"
[[constraint]]
  name = "github.com/go-yaml/yaml"
  version = "2.2.1"

[[constraint]]
  name = "github.com/imroc/req"
  version = "0.2.1"

[[constraint]]
  name = "github.com/homee-engineering/go-commons"
  version = "1.2.7"

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.3.6"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/ory/dockertest"
  version = "3.3.2"

[[constraint]]
  name = "github.com/olivere/elastic"
  version = "6.2.11"
